### ISSUE TITLE
Need to download docker compose

### ISSUE THREAD

**Issue by aedward8** [gsong/express-react-project-example#1]
https://formulae.brew.sh/formula/docker-compose

I was thrown an error when trying to run 
npm run init:db

I downloaded docker-compose through homebrew since I also downloaded docker through homebrew.

I am still getting thrown a dockers related error 

~
raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
npm ERR! code 1
npm ERR! path /Users/tpl1_2021h1/Desktop/Techtonica/Techtonica_Local_Only/express-react-project-example
npm ERR! command failed
npm ERR! command sh -c docker-compose down
~

**Comment by gsong** [comment]
@aedward8 Let's look at your environment together, when you do `brew install docker` that comes with `docker-compose`.
